import { z } from 'zod';

/** Opaque string IDs (ULID/UUID). Generated by application code, not D1. */
export const IdSchema = z.string().min(1).max(64);

export const EmailAddressSchema = z.string().email().max(320);

export const IsoDateTimeSchema = z.string().datetime();

export const MessageDirectionSchema = z.enum(['inbound', 'outbound']);
export type MessageDirection = z.infer<typeof MessageDirectionSchema>;

export const MessageStatusSchema = z.enum([
  'received',
  'sending',
  'sent',
  'failed',
  'draft',
]);
export type MessageStatus = z.infer<typeof MessageStatusSchema>;

export const RecipientTypeSchema = z.enum(['to', 'cc', 'bcc']);
export type RecipientType = z.infer<typeof RecipientTypeSchema>;

export const MailboxUserRoleSchema = z.enum(['owner', 'member']);
export type MailboxUserRole = z.infer<typeof MailboxUserRoleSchema>;

export const DevicePlatformSchema = z.enum(['web', 'desktop', 'ios', 'android']);
export type DevicePlatform = z.infer<typeof DevicePlatformSchema>;

export const SettingsScopeSchema = z.enum(['user', 'mailbox']);
export type SettingsScope = z.infer<typeof SettingsScopeSchema>;

export const SystemLabelSlugSchema = z.enum([
  'inbox',
  'sent',
  'drafts',
  'archive',
  'trash',
  'spam',
]);
export type SystemLabelSlug = z.infer<typeof SystemLabelSlugSchema>;
